
logMaxLine: 100
logFolderName: Log

# #object array
# array:
#     - apple
#     - banana
#     - 12345
#     - a: b
#     - b: b
  
# json style array: ["apple", banana, 12345, a: b]

# #array
# values:
#     - 1
#     - 2
#     - 3
